import mongoose from "mongoose";

// ═══════════════════════════════════════════════════════════════
// TRACE: El Tony Mate 330ml
// Barcode: 7640150491001
// BatchId: L250634716:41
// Hersteller: intelligentfood AG, Zürich
// Produkt: Cold Brew Mate-Tee aus Argentinien/Südamerika
// ═══════════════════════════════════════════════════════════════

export const EL_TONY_TRACE_ID = new mongoose.Types.ObjectId("64a1b2c3d4e5f6a7b8c9a005");

export const elTonyMateTrace = {
  _id:               EL_TONY_TRACE_ID,
  barcode:           "7640150491001",
  batchId:           "L250634716:41",
  generatedAt:       new Date("2025-06-03T08:00:00Z"),
  requiresColdChain: false,
  alertIds:          [],

  stations: [

    // ── Station 1: Yerba Mate Ernte — Argentinien ─────────────────
    {
      id:            "sta-eltony-001",
      type:          "farming",
      status:        "completed",
      title:         "Yerba Mate Ernte Misiones",
      subtitle:      "Provinz Misiones, Argentinien",
      startedAt:     new Date("2024-10-01T00:00:00Z"),
      completedAt:   new Date("2024-11-30T00:00:00Z"),
      durationHours: 1464,
      co2KgPerKg:    1.2,
      isVerified:    true,
      verifiedBy:    "Rainforest Alliance",
      notes:         "Traditioneller Anbau in der feuchten subtropischen Klimazone. Schattenanbau unter Baumkronen.",
      wasRefrigerated: false,
      refrigerationTemperatureCelsius: null,
      certificationIds: ["cert-eltony-ra-001"],
      location: {
        name:      "Cooperativa Mate Misiones",
        country:   "AR",
        region:    "Misiones",
        city:      "Posadas",
        address:   null,
        latitude:  -27.3621,
        longitude: -55.8938,
        embCode:   null,
        gln:       null,
      },
      qualityChecks: [
        {
          id:                  "qc-eltony-001",
          type:                "chemical",
          status:              "passed",
          performedAt:         new Date("2024-12-05T10:00:00Z"),
          performedBy:         "SGS Argentina SA",
          accreditationNumber: "OAA-LA-0045",
          reportNumber:        "SGS-ARG-2024-1205",
          resultSummary:       "Keine Pestizid-Rückstände über EU-Grenzwerten. Koffeingehalt 23mg/100ml bestätigt.",
          nextCheckDue:        null,
          isMandatory:         true,
          detail: {
            laboratoryName: "SGS Argentina SA",
            testMethod:     "LC-MS/MS",
            substancesTested: [
              { substance: "Glyphosat",    category: "herbicide",   measuredMgPerKg: 0.001, limitMgPerKg: 0.1,  limitExceeded: false, status: "passed" },
              { substance: "Chlorpyrifos", category: "insecticide", measuredMgPerKg: 0.000, limitMgPerKg: 0.01, limitExceeded: false, status: "passed" },
              { substance: "Imidacloprid", category: "insecticide", measuredMgPerKg: 0.002, limitMgPerKg: 0.05, limitExceeded: false, status: "passed" },
            ],
          },
        },
      ],
      environmentSummary: {
        co2KgPerKg:      1.2,
        waterLiterPerKg: 850,
        energyKwhPerKg:  0.4,
        landUseM2PerKg:  8.5,
      },
      detail: {
        farmName:                "Cooperativa Mate Misiones",
        farmingMethod:           "conventional",
        husbandrySystem:         null,
        fertilizerType:          "organic",
        irrigationType:          "rain-fed",
        cropYieldTonsPerHectare: 6.5,
        pesticidesUsed:          false,
        organicCertified:        false,
        fieldCoordinates: [
          { latitude: -27.3621, longitude: -55.8938, areaHectares: 320.0 },
        ],
      },
    },

    // ── Station 2: Guarana-Anbau — Brasilien ──────────────────────
    {
      id:            "sta-eltony-002",
      type:          "farming",
      status:        "completed",
      title:         "Guarana-Anbau Maués",
      subtitle:      "Amazonas, Brasilien",
      startedAt:     new Date("2024-08-01T00:00:00Z"),
      completedAt:   new Date("2024-10-15T00:00:00Z"),
      durationHours: 1836,
      co2KgPerKg:    0.8,
      isVerified:    false,
      verifiedBy:    null,
      notes:         "Guaranaextrakt 0.1% im Endprodukt. Natürliche Koffeinquelle.",
      wasRefrigerated: false,
      refrigerationTemperatureCelsius: null,
      certificationIds: [],
      location: {
        name:      "Associação dos Produtores de Guaraná de Maués",
        country:   "BR",
        region:    "Amazonas",
        city:      "Maués",
        address:   null,
        latitude:  -3.3842,
        longitude: -57.7178,
        embCode:   null,
        gln:       null,
      },
      qualityChecks: [],
      environmentSummary: {
        co2KgPerKg:      0.8,
        waterLiterPerKg: 1200,
        energyKwhPerKg:  0.3,
        landUseM2PerKg:  12.0,
      },
      detail: {
        farmName:                "Associação Maués",
        farmingMethod:           "conventional",
        husbandrySystem:         null,
        fertilizerType:          "organic",
        irrigationType:          "rain-fed",
        cropYieldTonsPerHectare: 0.3,
        pesticidesUsed:          false,
        organicCertified:        false,
        fieldCoordinates: [
          { latitude: -3.3842, longitude: -57.7178, areaHectares: 45.0 },
        ],
      },
    },

    // ── Station 3: Rohrzucker — Brasilien ─────────────────────────
    {
      id:            "sta-eltony-003",
      type:          "processing",
      status:        "completed",
      title:         "Bio-Rohrzucker Produktion",
      subtitle:      "São Paulo State, Brasilien",
      startedAt:     new Date("2025-01-10T06:00:00Z"),
      completedAt:   new Date("2025-01-20T18:00:00Z"),
      durationHours: 252,
      co2KgPerKg:    0.35,
      isVerified:    true,
      verifiedBy:    "Bureau Veritas Brasil",
      notes:         "Biologischer Rohrzucker, EU-Bio-Zertifizierung. Keine Bleichung oder chemische Raffination.",
      wasRefrigerated: false,
      refrigerationTemperatureCelsius: null,
      certificationIds: ["cert-eltony-bio-001"],
      location: {
        name:      "Usina São Martinho",
        country:   "BR",
        region:    "São Paulo",
        city:      "Pradópolis",
        address:   null,
        latitude:  -21.3667,
        longitude: -48.0667,
        embCode:   null,
        gln:       null,
      },
      qualityChecks: [],
      environmentSummary: {
        co2KgPerKg:      0.35,
        waterLiterPerKg: 180,
        energyKwhPerKg:  0.9,
        landUseM2PerKg:  null,
      },
      detail: {
        processType:        "refining",
        facilityName:       "Usina São Martinho",
        haccp:              true,
        foodSafetyStandard: "FSSC22000",
      },
    },

    // ── Station 4: Cold Brew & Abfüllung — Zürich ─────────────────
    {
      id:            "sta-eltony-004",
      type:          "processing",
      status:        "completed",
      title:         "Cold Brew & Abfüllung Zürich",
      subtitle:      "intelligentfood AG, Zürich",
      startedAt:     new Date("2025-06-01T06:00:00Z"),
      completedAt:   new Date("2025-06-03T14:00:00Z"),
      durationHours: 56,
      co2KgPerKg:    0.09,
      isVerified:    true,
      verifiedBy:    "SGS SA Zürich",
      notes:         "Cold Brew Verfahren: Mate-Tee wird bei 4°C für 12-24h aufgebrüht. Charge L250634716:41. Pasteurisiert.",
      wasRefrigerated: true,
      refrigerationTemperatureCelsius: 4,
      certificationIds: ["cert-eltony-iso22000-001"],
      location: {
        name:      "intelligentfood AG",
        country:   "CH",
        region:    "Zürich",
        city:      "Zürich",
        address:   "Hardturmstrasse 161, 8005 Zürich",
        latitude:   47.3892,
        longitude:  8.5190,
        embCode:   "CH-ZH 015 EG",
        gln:       "7640150490001",
      },
      qualityChecks: [
        {
          id:                  "qc-eltony-002",
          type:                "microbiological",
          status:              "passed",
          performedAt:         new Date("2025-06-03T07:00:00Z"),
          performedBy:         "intelligentfood AG QC Labor",
          accreditationNumber: "STS 0612",
          reportNumber:        "IFG-QC-2025-L250634716",
          resultSummary:       "Keine pathogenen Keime nachgewiesen. Koffeingehalt 23mg/100ml. pH 3.8. Pasteurisiert.",
          nextCheckDue:        new Date("2025-09-03T00:00:00Z"),
          isMandatory:         true,
          detail: {
            laboratoryName:     "intelligentfood AG Internes Labor",
            iso17025Accredited: true,
            pathogensTested: [
              { pathogen: "E. coli",                  testMethod: "ISO 16649", detected: false, cfuPerGram: 0,  euLimitCfuPerGram: 100, limitExceeded: false, status: "passed" },
              { pathogen: "Salmonella spp.",           testMethod: "ISO 6579",  detected: false, cfuPerGram: 0,  euLimitCfuPerGram: 0,   limitExceeded: false, status: "passed" },
              { pathogen: "Listeria monocytogenes",    testMethod: "ISO 11290", detected: false, cfuPerGram: 0,  euLimitCfuPerGram: 0,   limitExceeded: false, status: "passed" },
            ],
          },
        },
        {
          id:                  "qc-eltony-003",
          type:                "nutritional",
          status:              "passed",
          performedAt:         new Date("2025-06-03T08:00:00Z"),
          performedBy:         "SQTS Swiss Quality Testing Services",
          accreditationNumber: "STS 0492",
          reportNumber:        "SQTS-2025-0603-001",
          resultSummary:       "Nährwerte innerhalb EU-Toleranz. Koffeingehalt und Guaranagehalt deklarationskonform.",
          nextCheckDue:        null,
          isMandatory:         true,
          detail: {
            laboratoryName: "SQTS Swiss Quality Testing Services",
            measuredValues: {
              energyKcal100g:    24,
              fat100g:           0.5,
              saturatedFat100g:  0.1,
              carbohydrates100g: 5.8,
              sugars100g:        5.8,
              proteins100g:      0.5,
              salt100g:          0.01,
              fiber100g:         null,
            },
          },
        },
      ],
      environmentSummary: {
        co2KgPerKg:      0.09,
        waterLiterPerKg: 3.2,
        energyKwhPerKg:  0.18,
        landUseM2PerKg:  null,
      },
      detail: {
        processType:        "bottling",
        facilityName:       "intelligentfood AG Zürich",
        haccp:              true,
        foodSafetyStandard: "IFS",
      },
    },

    // ── Station 5: Transport CH-Lager → Detailhandel ──────────────
    {
      id:            "sta-eltony-005",
      type:          "transport",
      status:        "completed",
      title:         "Logistik Schweiz",
      subtitle:      "Lager → Coop / Migros Filialen",
      startedAt:     new Date("2025-06-04T04:00:00Z"),
      completedAt:   new Date("2025-06-04T18:00:00Z"),
      durationHours: 14,
      co2KgPerKg:    0.03,
      isVerified:    false,
      verifiedBy:    null,
      notes:         "Kühlunbedürftiges Produkt. Raumtemperatur-Transport.",
      wasRefrigerated: false,
      refrigerationTemperatureCelsius: null,
      certificationIds: [],
      location:      null,
      qualityChecks: [],
      environmentSummary: {
        co2KgPerKg:      0.03,
        waterLiterPerKg: null,
        energyKwhPerKg:  0.02,
        landUseM2PerKg:  null,
      },
      detail: {
        mode:           "road",
        carrierName:    "Planzer Transport AG",
        distanceKm:     180,
        fuelType:       "diesel",
        co2EmissionsKg: 0.03,
        tempControlled: false,
        tempMinCelsius: null,
        tempMaxCelsius: null,
      },
    },

    // ── Station 6: Retail — Coop Zürich ───────────────────────────
    {
      id:            "sta-eltony-006",
      type:          "retail",
      status:        "completed",
      title:         "Coop City Zürich Bellevue",
      subtitle:      "Einzelhandel Schweiz",
      startedAt:     new Date("2025-06-05T05:00:00Z"),
      completedAt:   null,
      durationHours: null,
      co2KgPerKg:    0.02,
      isVerified:    false,
      verifiedBy:    null,
      notes:         null,
      wasRefrigerated: false,
      refrigerationTemperatureCelsius: null,
      certificationIds: [],
      location: {
        name:      "Coop City Zürich Bellevue",
        country:   "CH",
        region:    "Zürich",
        city:      "Zürich",
        address:   "Theaterstrasse 12, 8001 Zürich",
        latitude:   47.3663,
        longitude:  8.5447,
        embCode:   null,
        gln:       "7610200020001",
      },
      qualityChecks: [],
      environmentSummary: null,
      detail: {
        storeName:        "Coop City Zürich Bellevue",
        storeChain:       "Coop",
        storeGln:         "7610200020001",
        displayType:      "shelf",
        shelfTempCelsius: 18,
        retailerId:       "64a1b2c3d4e5f6a7b8c9e002", // Coop Retailer ID aus Seed
      },
    },
  ],

  environmentSummary: {
    co2TotalKgPerKg:            1.49,
    ecoscoreGrade:              "b",
    ecoscoreScore:              61,
    waterFootprintLiterPerKg:   1240,
    waterStressScore:           0.38,
    forestFootprintM2PerKg:     0.12,
    forestFootprintGrade:       "b",
    deforestationRisk:          0.18,
    transportEmissionsGramsCo2: 48,
    totalTransportDistanceKm:   12500,
    transportLegCount:          3,
    packagingCo2Kg:             0.065,
    packagingScore:             68,
    recyclablePackagingPercent: 1.0,
    productionSystemBonus:      3,
    originEpiScore:             52,
    co2ByPhase: {
      agriculture:    1.2,
      processing:     0.09,
      transportation: 0.048,
      packaging:      0.065,
      distribution:   0.03,
      consumption:    null,
    },
    threatenedSpeciesRisk: null,
  },

  certifications: [
    {
      id:               "cert-eltony-ra-001",
      type:             "RainforestAlliance",
      scope:            "farming",
      source:           "third-party",
      issuedBy:         "Rainforest Alliance",
      issuedAt:         new Date("2024-09-01T00:00:00Z"),
      validUntil:       new Date("2025-08-31T00:00:00Z"),
      certificateUrl:   "https://www.rainforest-alliance.org/certificate/eltony-mate-001",
      verifiedByTomapo: false,
    },
    {
      id:               "cert-eltony-bio-001",
      type:             "EUOrganic",
      scope:            "ingredient",
      source:           "third-party",
      issuedBy:         "Bio Suisse",
      issuedAt:         new Date("2025-01-01T00:00:00Z"),
      validUntil:       new Date("2025-12-31T00:00:00Z"),
      certificateUrl:   null,
      verifiedByTomapo: false,
    },
    {
      id:               "cert-eltony-iso22000-001",
      type:             "ISO22000",
      scope:            "food-safety",
      source:           "third-party",
      issuedBy:         "SGS SA",
      issuedAt:         new Date("2024-03-01T00:00:00Z"),
      validUntil:       new Date("2027-03-01T00:00:00Z"),
      certificateUrl:   "https://www.sgs.com/certifications/iso22000/intelligentfood-001",
      verifiedByTomapo: true,
    },
  ],

  traceabilityScore: {
    completeness:          0.82,
    verifiedStations:      3,
    unknownStations:       1,
    hasGaps:               false,
    isThirdPartyVerified:  true,
    blockchainHash:        null,
  },

  dataSources: [
    { id: "ds-eltony-001", type: "manufacturer", reliability: "high",   name: "intelligentfood AG",  url: "https://www.eltonymate.com",         fetchedAt: new Date("2025-06-03T08:00:00Z") },
    { id: "ds-eltony-002", type: "openFoodFacts", reliability: "medium", name: "Open Food Facts",    url: "https://world.openfoodfacts.org",    fetchedAt: new Date("2025-06-03T08:01:00Z") },
    { id: "ds-eltony-003", type: "retailer",      reliability: "medium", name: "Coop Schweiz",       url: "https://www.coop.ch",               fetchedAt: new Date("2025-06-03T08:02:00Z") },
  ],

  coldChainSummary: null,

  ingredients: [
    {
      ingredientType: "subProduct",
      chemical:       null,
      subProduct: {
        barcode:         null,
        productName:     "Yerba Mate Tee (Cold Brew Aufguss 90%)",
        brand:           null,
        category:        "tea",
        percentMin:      85,
        percentMax:      92,
        percentEstimate: 90,
        isTraceable:     true,
        originCountry:   "AR",
      },
    },
    {
      ingredientType: "subProduct",
      chemical:       null,
      subProduct: {
        barcode:         null,
        productName:     "Bio-Rohrzucker",
        brand:           null,
        category:        "sweetener",
        percentMin:      4,
        percentMax:      7,
        percentEstimate: 5.8,
        isTraceable:     true,
        originCountry:   "BR",
      },
    },
    {
      ingredientType: "subProduct",
      chemical:       null,
      subProduct: {
        barcode:         null,
        productName:     "Zitronensaft aus Konzentrat (3%)",
        brand:           null,
        category:        "fruit-juice",
        percentMin:      3,
        percentMax:      3,
        percentEstimate: 3,
        isTraceable:     false,
        originCountry:   null,
      },
    },
    {
      ingredientType: "chemical",
      subProduct:     null,
      chemical: {
        name:                    "Guaranaextrakt",
        eNumber:                 null,
        casNumber:               "84929-28-2",
        category:                "stimulants",
        function:                "flavouring",
        origin:                  "natural",
        euStatus:                "permitted",
        healthAssessment:        "safe-within-adi",
        concentrationMgPerKg:    1.0,
        adAcceptableDailyIntake: null,
      },
    },
    {
      ingredientType: "chemical",
      subProduct:     null,
      chemical: {
        name:                    "Koffein (natürlich aus Guarana und Mate)",
        eNumber:                 null,
        casNumber:               "58-08-2",
        category:                "stimulants",
        function:                "flavouring",
        origin:                  "natural",
        euStatus:                "permitted",
        healthAssessment:        "safe-within-adi",
        concentrationMgPerKg:    230,
        adAcceptableDailyIntake: 3,
      },
    },
  ],

  createdAt: new Date("2025-06-03T08:00:00Z"),
  updatedAt: new Date("2025-06-03T08:00:00Z"),
};

// ─── Seed-Funktion ────────────────────────────────────────────────

export async function seedElTonyMate() {
  const db = mongoose.connection.db;
  await db.collection("traces").insertOne(elTonyMateTrace);
  console.log("   ✓ El Tony Mate Trace inserted (barcode: 7640150491001, batch: L250634716:41)");
  return elTonyMateTrace;
}