import mongoose from "mongoose";
import { USER_IDS } from "./User.seed.js";
import { PRODUCT_BARCODES } from "./constants.seed.js";

export async function seedScanHistory(users, products, traces) {
  const db = mongoose.connection.db;

  const entries = [
    // ── Max Müller — aktiver Nutzer, scannt oft ───────────────────
    {
      _id:           new mongoose.Types.ObjectId(),
      userId:        USER_IDS.maxMueller,
      barcode:       PRODUCT_BARCODES.lindt85,
      barcodeType:   "EAN13",
      batchId:       "LINDT-85-2026-0201",
      productName:   "Lindt Excellence 85% Cacao",
      brand:         "Lindt",
      imageUrl:      "https://images.openfoodfacts.org/images/products/304/692/002/8836/front_de.12.400.jpg",
      nutriscoreGrade: "d",
      ecoscoreGrade:   "c",
      co2KgPerKg:    2.75,
      productStatus: "recallActive",
      bestBeforeDate: new Date("2028-01-01T00:00:00Z"),
      scannedAt:     new Date("2026-03-12T19:55:00Z"),
      createdAt:     new Date("2026-03-12T19:55:00Z"),
    },
    {
      _id:           new mongoose.Types.ObjectId(),
      userId:        USER_IDS.maxMueller,
      barcode:       PRODUCT_BARCODES.cocaCola,
      barcodeType:   "EAN13",
      batchId:       "CC-CH-2026-0312",
      productName:   "Coca-Cola Original Taste",
      brand:         "Coca-Cola",
      imageUrl:      "https://images.openfoodfacts.org/images/products/544/900/000/0996/front_de.8.400.jpg",
      nutriscoreGrade: "e",
      ecoscoreGrade:   "c",
      co2KgPerKg:    0.24,
      productStatus: "ok",
      bestBeforeDate: new Date("2026-09-30T00:00:00Z"),
      scannedAt:     new Date("2026-03-20T13:10:00Z"),
      createdAt:     new Date("2026-03-20T13:10:00Z"),
    },
    {
      _id:           new mongoose.Types.ObjectId(),
      userId:        USER_IDS.maxMueller,
      barcode:       PRODUCT_BARCODES.ovomaltine,
      barcodeType:   "EAN13",
      batchId:       null,
      productName:   "Ovomaltine Pulver",
      brand:         "Wander",
      imageUrl:      "https://images.openfoodfacts.org/images/products/761/030/500/1002/front_de.10.400.jpg",
      nutriscoreGrade: "c",
      ecoscoreGrade:   "b",
      co2KgPerKg:    2.12,
      productStatus: "ok",
      bestBeforeDate: new Date("2027-08-01T00:00:00Z"),
      scannedAt:     new Date("2026-03-22T08:30:00Z"),
      createdAt:     new Date("2026-03-22T08:30:00Z"),
    },
    {
      _id:           new mongoose.Types.ObjectId(),
      userId:        USER_IDS.maxMueller,
      barcode:       PRODUCT_BARCODES.migrosMilch,
      barcodeType:   "EAN13",
      batchId:       "MILCH-2026-0320",
      productName:   "M-Classic Vollmilch",
      brand:         "M-Classic, Migros",
      imageUrl:      "https://images.openfoodfacts.org/images/products/761/081/500/1032/front_de.6.400.jpg",
      nutriscoreGrade: "b",
      ecoscoreGrade:   "c",
      co2KgPerKg:    2.0,
      productStatus: "ok",
      bestBeforeDate: new Date("2026-03-27T00:00:00Z"),
      scannedAt:     new Date("2026-03-24T17:45:00Z"),
      createdAt:     new Date("2026-03-24T17:45:00Z"),
    },

    // ── Lara Schmid ───────────────────────────────────────────────
    {
      _id:           new mongoose.Types.ObjectId(),
      userId:        USER_IDS.laraSchmid,
      barcode:       PRODUCT_BARCODES.ovomaltine,
      barcodeType:   "EAN13",
      batchId:       "OVO-2026-0301",
      productName:   "Ovomaltine Pulver",
      brand:         "Wander",
      imageUrl:      "https://images.openfoodfacts.org/images/products/761/030/500/1002/front_de.10.400.jpg",
      nutriscoreGrade: "c",
      ecoscoreGrade:   "b",
      co2KgPerKg:    2.12,
      productStatus: "ok",
      bestBeforeDate: new Date("2027-08-01T00:00:00Z"),
      scannedAt:     new Date("2026-03-20T18:55:00Z"),
      createdAt:     new Date("2026-03-20T18:55:00Z"),
    },
    {
      _id:           new mongoose.Types.ObjectId(),
      userId:        USER_IDS.laraSchmid,
      barcode:       PRODUCT_BARCODES.lindt85,
      barcodeType:   "EAN13",
      batchId:       null,
      productName:   "Lindt Excellence 85% Cacao",
      brand:         "Lindt",
      imageUrl:      "https://images.openfoodfacts.org/images/products/304/692/002/8836/front_de.12.400.jpg",
      nutriscoreGrade: "d",
      ecoscoreGrade:   "c",
      co2KgPerKg:    2.75,
      productStatus: "recallActive",
      bestBeforeDate: new Date("2028-01-01T00:00:00Z"),
      scannedAt:     new Date("2026-03-25T11:00:00Z"),
      createdAt:     new Date("2026-03-25T11:00:00Z"),
    },

    // ── Timo Keller ───────────────────────────────────────────────
    {
      _id:           new mongoose.Types.ObjectId(),
      userId:        USER_IDS.timoKeller,
      barcode:       PRODUCT_BARCODES.cocaCola,
      barcodeType:   "EAN13",
      batchId:       null,
      productName:   "Coca-Cola Original Taste",
      brand:         "Coca-Cola",
      imageUrl:      "https://images.openfoodfacts.org/images/products/544/900/000/0996/front_de.8.400.jpg",
      nutriscoreGrade: "e",
      ecoscoreGrade:   "c",
      co2KgPerKg:    0.24,
      productStatus: "ok",
      bestBeforeDate: new Date("2026-10-01T00:00:00Z"),
      scannedAt:     new Date("2026-03-16T12:28:00Z"),
      createdAt:     new Date("2026-03-16T12:28:00Z"),
    },
    {
      _id:           new mongoose.Types.ObjectId(),
      userId:        USER_IDS.timoKeller,
      barcode:       PRODUCT_BARCODES.rivella,
      barcodeType:   "EAN13",
      batchId:       null,
      productName:   "Rivella Rot",
      brand:         "Rivella",
      imageUrl:      "https://images.openfoodfacts.org/images/products/761/082/000/0107/front_de.6.400.jpg",
      nutriscoreGrade: "d",
      ecoscoreGrade:   "c",
      co2KgPerKg:    null,
      productStatus: "ok",
      bestBeforeDate: new Date("2026-12-01T00:00:00Z"),
      scannedAt:     new Date("2026-03-18T15:20:00Z"),
      createdAt:     new Date("2026-03-18T15:20:00Z"),
    },

    // ── Sofia Rossi ───────────────────────────────────────────────
    {
      _id:           new mongoose.Types.ObjectId(),
      userId:        USER_IDS.sofiaRossi,
      barcode:       PRODUCT_BARCODES.migrosMilch,
      barcodeType:   "EAN13",
      batchId:       "MILCH-2026-0320",
      productName:   "M-Classic Vollmilch",
      brand:         "M-Classic, Migros",
      imageUrl:      "https://images.openfoodfacts.org/images/products/761/081/500/1032/front_de.6.400.jpg",
      nutriscoreGrade: "b",
      ecoscoreGrade:   "c",
      co2KgPerKg:    2.0,
      productStatus: "mhdSoonExpiring",
      bestBeforeDate: new Date("2026-03-26T00:00:00Z"),
      scannedAt:     new Date("2026-03-24T09:05:00Z"),
      createdAt:     new Date("2026-03-24T09:05:00Z"),
    },
  ];

  await db.collection("scan_history").insertMany(entries);
  console.log(`   ✓ ScanHistory: ${entries.length} inserted`);
  return entries;
}