import mongoose from "mongoose";
import { PRODUCT_BARCODES } from "./constants.seed.js";

export const TRACE_IDS = {
  cocaCola:   new mongoose.Types.ObjectId("64a1b2c3d4e5f6a7b8c9a001"),
  ovomaltine: new mongoose.Types.ObjectId("64a1b2c3d4e5f6a7b8c9a002"),
  milch:      new mongoose.Types.ObjectId("64a1b2c3d4e5f6a7b8c9a003"),
  lindt:      new mongoose.Types.ObjectId("64a1b2c3d4e5f6a7b8c9a004"),
};

export async function seedTraces(products) {
  const db = mongoose.connection.db;

  const traces = [

    // ═══════════════════════════════════════════════════
    // TRACE 1: Coca-Cola — Belgien → Schweiz
    // ═══════════════════════════════════════════════════
    {
      _id:               TRACE_IDS.cocaCola,
      barcode:           PRODUCT_BARCODES.cocaCola,
      batchId:           "CC-CH-2026-0312",
      generatedAt:       new Date("2026-03-12T06:00:00Z"),
      requiresColdChain: false,
      alertIds:          [],
      stations: [
        {
          id:          "sta-cc-001",
          type:        "processing",
          status:      "completed",
          title:       "Abfüllung Brüttisellen",
          subtitle:    "Abfüllanlage Schweiz",
          startedAt:   new Date("2026-03-10T06:00:00Z"),
          completedAt: new Date("2026-03-10T22:00:00Z"),
          durationHours: 16,
          co2KgPerKg:   0.18,
          isVerified:   true,
          verifiedBy:   "Coca-Cola HBC Schweiz AG",
          notes:        "ISO 22000 zertifizierte Abfüllanlage",
          wasRefrigerated: false,
          refrigerationTemperatureCelsius: null,
          certificationIds: ["cert-iso22000-001"],
          location: {
            name:      "Coca-Cola HBC Schweiz AG",
            country:   "CH",
            region:    "Zürich",
            city:      "Brüttisellen",
            address:   "Stationsstrasse 33, 8306 Brüttisellen",
            latitude:   47.4250,
            longitude:  8.6236,
            embCode:    null,
            gln:        "7610305000001",
          },
          qualityChecks: [
            {
              id:          "qc-cc-001",
              type:        "microbiological",
              status:      "passed",
              performedAt: new Date("2026-03-10T08:00:00Z"),
              performedBy: "QC Labor Brüttisellen",
              accreditationNumber: "STS 0459",
              reportNumber: "QC-2026-0310-001",
              resultSummary: "Keine pathogenen Keime nachgewiesen",
              nextCheckDue: new Date("2026-06-10T08:00:00Z"),
              isMandatory: true,
              detail: {
                laboratoryName: "Coca-Cola Internes Labor",
                iso17025Accredited: true,
                pathogensTested: [
                  { pathogen: "E. coli", testMethod: "PCR", detected: false, cfuPerGram: 0, euLimitCfuPerGram: 100, limitExceeded: false, status: "passed" },
                  { pathogen: "Salmonella spp.", testMethod: "ISO 6579", detected: false, cfuPerGram: 0, euLimitCfuPerGram: 0, limitExceeded: false, status: "passed" },
                ],
              },
            },
          ],
          environmentSummary: { co2KgPerKg: 0.18, waterLiterPerKg: 2.1, energyKwhPerKg: 0.12, landUseM2PerKg: null },
          detail: {
            processType:        "bottling",
            facilityName:       "Coca-Cola HBC Brüttisellen",
            haccp:              true,
            foodSafetyStandard: "FSSC22000",
          },
        },
        {
          id:          "sta-cc-002",
          type:        "distribution",
          status:      "completed",
          title:       "Verteilung Zürich Lager",
          subtitle:    "Regionallager Ostschweiz",
          startedAt:   new Date("2026-03-11T04:00:00Z"),
          completedAt: new Date("2026-03-11T18:00:00Z"),
          durationHours: 14,
          co2KgPerKg:   0.04,
          isVerified:   true,
          verifiedBy:   "Coca-Cola Distribution CH",
          notes:        null,
          wasRefrigerated: false,
          refrigerationTemperatureCelsius: null,
          certificationIds: [],
          location: {
            name:     "Coca-Cola Lager Zürich",
            country:  "CH",
            region:   "Zürich",
            city:     "Dietlikon",
            address:  "Industriestrasse 10, 8305 Dietlikon",
            latitude:  47.4100,
            longitude: 8.6400,
            embCode:   null,
            gln:       "7610305000002",
          },
          qualityChecks: [],
          environmentSummary: { co2KgPerKg: 0.04, waterLiterPerKg: null, energyKwhPerKg: 0.03, landUseM2PerKg: null },
          detail: {
            centerType:           "regional-distribution-center",
            centerName:           "CDC Zürich-Ost",
            ordersProcessed:      4820,
            avgHandlingTimeHours: 1.5,
          },
        },
        {
          id:          "sta-cc-003",
          type:        "retail",
          status:      "completed",
          title:       "Migros Filiale Zürich HB",
          subtitle:    "Einzelhandel",
          startedAt:   new Date("2026-03-12T05:00:00Z"),
          completedAt: null,
          durationHours: null,
          co2KgPerKg:   0.02,
          isVerified:   false,
          verifiedBy:   null,
          notes:        null,
          wasRefrigerated: false,
          refrigerationTemperatureCelsius: null,
          certificationIds: [],
          location: {
            name:     "Migros Zürich HB",
            country:  "CH",
            region:   "Zürich",
            city:     "Zürich",
            address:  "Shopville, 8001 Zürich",
            latitude:  47.3778,
            longitude: 8.5403,
            embCode:   null,
            gln:       "7610200000001",
          },
          qualityChecks: [],
          environmentSummary: null,
          detail: {
            storeName:     "Migros Zürich HB",
            storeChain:    "Migros",
            storeGln:      "7610200000001",
            displayType:   "shelf",
            shelfTempCelsius: 18,
            retailerId:    "64a1b2c3d4e5f6a7b8c9e001",
          },
        },
      ],
      environmentSummary: {
        co2TotalKgPerKg:            0.24,
        ecoscoreGrade:              "c",
        ecoscoreScore:              43,
        waterFootprintLiterPerKg:   210,
        waterStressScore:           0.32,
        forestFootprintM2PerKg:     null,
        forestFootprintGrade:       null,
        deforestationRisk:          null,
        transportEmissionsGramsCo2: 38,
        totalTransportDistanceKm:   85,
        transportLegCount:          2,
        packagingCo2Kg:             0.052,
        packagingScore:             55,
        recyclablePackagingPercent: 1.0,
        productionSystemBonus:      null,
        originEpiScore:             null,
        co2ByPhase: {
          agriculture:    null,
          processing:     0.18,
          transportation: 0.04,
          packaging:      0.052,
          distribution:   0.04,
          consumption:    null,
        },
        threatenedSpeciesRisk: null,
      },
      certifications: [
        {
          id:              "cert-iso22000-001",
          type:            "ISO22000",
          scope:           "food-safety",
          source:          "third-party",
          issuedBy:        "SGS SA",
          issuedAt:        new Date("2024-06-01T00:00:00Z"),
          validUntil:      new Date("2027-06-01T00:00:00Z"),
          certificateUrl:  "https://www.sgs.com/certifications/iso22000/cc-ch-001",
          verifiedByTomapo: true,
        },
      ],
      traceabilityScore: {
        completeness:         0.82,
        verifiedStations:     2,
        unknownStations:      0,
        hasGaps:              false,
        isThirdPartyVerified: true,
        blockchainHash:       null,
      },
      dataSources: [
        { id: "ds-cc-001", type: "manufacturer", reliability: "high", name: "Coca-Cola HBC Schweiz", url: "https://www.coca-cola.ch", fetchedAt: new Date("2026-03-12T06:00:00Z") },
        { id: "ds-cc-002", type: "openFoodFacts", reliability: "medium", name: "Open Food Facts", url: "https://world.openfoodfacts.org", fetchedAt: new Date("2026-03-12T06:01:00Z") },
      ],
      coldChainSummary: null,
      ingredients: [
        { ingredientType: "chemical", subProduct: null, chemical: { name: "Koffein", eNumber: null, casNumber: "58-08-2", category: "stimulants", function: "flavouring", origin: "synthetic", euStatus: "permitted", healthAssessment: "safe-within-adi", concentrationMgPerKg: 120, adAcceptableDailyIntake: 3 } },
        { ingredientType: "chemical", subProduct: null, chemical: { name: "Phosphorsäure (E338)", eNumber: "E338", casNumber: "7664-38-2", category: "acidity-regulators", function: "acidity-regulator", origin: "synthetic", euStatus: "permitted", healthAssessment: "safe-within-adi", concentrationMgPerKg: null, adAcceptableDailyIntake: null } },
      ],
      createdAt: new Date("2026-03-12T06:00:00Z"),
      updatedAt: new Date("2026-03-12T06:00:00Z"),
    },

    // ═══════════════════════════════════════════════════
    // TRACE 2: Ovomaltine — Neuenegg → Schweiz
    // ═══════════════════════════════════════════════════
    {
      _id:               TRACE_IDS.ovomaltine,
      barcode:           PRODUCT_BARCODES.ovomaltine,
      batchId:           "OVO-2026-0301",
      generatedAt:       new Date("2026-03-05T07:00:00Z"),
      requiresColdChain: false,
      alertIds:          [],
      stations: [
        {
          id:          "sta-ovo-001",
          type:        "farming",
          status:      "completed",
          title:       "Gerstenerzeugung CH",
          subtitle:    "Anbau in der Schweiz",
          startedAt:   new Date("2025-05-01T00:00:00Z"),
          completedAt: new Date("2025-08-31T00:00:00Z"),
          durationHours: 2208,
          co2KgPerKg:   0.89,
          isVerified:   true,
          verifiedBy:   "IP-SUISSE",
          notes:        "Schweizer Sommergerste, IP-SUISSE zertifiziert",
          wasRefrigerated: false,
          refrigerationTemperatureCelsius: null,
          certificationIds: ["cert-ipsuisse-001"],
          location: {
            name:    "Hof Müller",
            country: "CH",
            region:  "Bern",
            city:    "Lyss",
            address: null,
            latitude:  47.0701,
            longitude: 7.3011,
            embCode: null,
            gln:     null,
          },
          qualityChecks: [
            {
              id:          "qc-ovo-001",
              type:        "chemical",
              status:      "passed",
              performedAt: new Date("2025-09-05T10:00:00Z"),
              performedBy: "Agroscope",
              accreditationNumber: "STS 0389",
              reportNumber: "AGRO-2025-0901",
              resultSummary: "Keine Pestizide über EU-Grenzwerten",
              nextCheckDue: null,
              isMandatory:  true,
              detail: {
                laboratoryName: "Agroscope Liebefeld",
                testMethod: "LC-MS/MS",
                substancesTested: [
                  { substance: "Glyphosat", category: "herbicide", measuredMgPerKg: 0.002, limitMgPerKg: 0.1, limitExceeded: false, status: "passed" },
                  { substance: "Chlorpyrifos", category: "insecticide", measuredMgPerKg: 0.001, limitMgPerKg: 0.01, limitExceeded: false, status: "passed" },
                ],
              },
            },
          ],
          environmentSummary: { co2KgPerKg: 0.89, waterLiterPerKg: 1200, energyKwhPerKg: 1.8, landUseM2PerKg: 2.1 },
          detail: {
            farmName:         "Hof Müller, Lyss",
            farmingMethod:    "integrated",
            husbandrySystem:  null,
            fertilizerType:   "mineral",
            irrigationType:   "none",
            cropYieldTonsPerHectare: 5.8,
            pesticidesUsed:   true,
            organicCertified: false,
            fieldCoordinates: [{ latitude: 47.0701, longitude: 7.3011, areaHectares: 4.2 }],
          },
        },
        {
          id:          "sta-ovo-002",
          type:        "processing",
          status:      "completed",
          title:       "Produktion Neuenegg",
          subtitle:    "Wander AG Hauptwerk",
          startedAt:   new Date("2026-02-20T06:00:00Z"),
          completedAt: new Date("2026-03-01T14:00:00Z"),
          durationHours: 248,
          co2KgPerKg:   1.2,
          isVerified:   true,
          verifiedBy:   "SGS SA",
          notes:        "IFS Food zertifiziertes Werk, Charge OVO-2026-0301",
          wasRefrigerated: false,
          refrigerationTemperatureCelsius: null,
          certificationIds: ["cert-ifs-001"],
          location: {
            name:     "Wander AG",
            country:  "CH",
            region:   "Bern",
            city:     "Neuenegg",
            address:  "Wander-Strasse 1, 3176 Neuenegg",
            latitude:  46.9000,
            longitude: 7.3167,
            embCode:  "CH-BE 001",
            gln:      "7610305000010",
          },
          qualityChecks: [
            {
              id:          "qc-ovo-002",
              type:        "nutritional",
              status:      "passed",
              performedAt: new Date("2026-02-28T09:00:00Z"),
              performedBy: "Wander QA Labor",
              accreditationNumber: "STS 0459",
              reportNumber: "WANDER-QC-2026-028",
              resultSummary: "Nährwertangaben innerhalb Toleranz",
              nextCheckDue: new Date("2026-05-28T09:00:00Z"),
              isMandatory:  true,
              detail: {
                laboratoryName: "Wander AG Internes Labor",
                measuredValues: {
                  energyKcal100g:    385,
                  fat100g:           6.6,
                  saturatedFat100g:  3.0,
                  carbohydrates100g: 67.1,
                  sugars100g:        38.2,
                  proteins100g:      14.1,
                  salt100g:          0.39,
                  fiber100g:         4.5,
                },
              },
            },
          ],
          environmentSummary: { co2KgPerKg: 1.2, waterLiterPerKg: 8.5, energyKwhPerKg: 2.3, landUseM2PerKg: null },
          detail: {
            processType:        "mixing",
            facilityName:       "Wander AG Neuenegg",
            haccp:              true,
            foodSafetyStandard: "IFS",
          },
        },
        {
          id:          "sta-ovo-003",
          type:        "retail",
          status:      "completed",
          title:       "Coop Supermarkt Bern",
          subtitle:    "POS Bern Zentrum",
          startedAt:   new Date("2026-03-05T05:00:00Z"),
          completedAt: null,
          durationHours: null,
          co2KgPerKg:   0.03,
          isVerified:   false,
          verifiedBy:   null,
          notes:        null,
          wasRefrigerated: false,
          refrigerationTemperatureCelsius: null,
          certificationIds: [],
          location: {
            name:     "Coop Bern Zentrum",
            country:  "CH",
            region:   "Bern",
            city:     "Bern",
            address:  "Neuengasse 23, 3011 Bern",
            latitude:  46.9481,
            longitude: 7.4474,
            embCode:   null,
            gln:       "7610200010001",
          },
          qualityChecks: [],
          environmentSummary: null,
          detail: {
            storeName:  "Coop Bern Zentrum",
            storeChain: "Coop",
            storeGln:   "7610200010001",
            displayType:"shelf",
            shelfTempCelsius: 18,
            retailerId: "64a1b2c3d4e5f6a7b8c9e002",
          },
        },
      ],
      environmentSummary: {
        co2TotalKgPerKg:            2.12,
        ecoscoreGrade:              "b",
        ecoscoreScore:              62,
        waterFootprintLiterPerKg:   1240,
        waterStressScore:           0.41,
        forestFootprintM2PerKg:     0.08,
        forestFootprintGrade:       "b",
        deforestationRisk:          0.12,
        transportEmissionsGramsCo2: 55,
        totalTransportDistanceKm:   180,
        transportLegCount:          3,
        packagingCo2Kg:             0.09,
        packagingScore:             72,
        recyclablePackagingPercent: 1.0,
        productionSystemBonus:      5,
        originEpiScore:             68,
        co2ByPhase: {
          agriculture:    0.89,
          processing:     1.2,
          transportation: 0.055,
          packaging:      0.09,
          distribution:   0.03,
          consumption:    null,
        },
        threatenedSpeciesRisk: null,
      },
      certifications: [
        {
          id:             "cert-ipsuisse-001",
          type:           "IP-SUISSE",
          scope:          "farming",
          source:         "third-party",
          issuedBy:       "IP-SUISSE",
          issuedAt:       new Date("2025-04-01T00:00:00Z"),
          validUntil:     new Date("2026-03-31T00:00:00Z"),
          certificateUrl: null,
          verifiedByTomapo: true,
        },
        {
          id:             "cert-ifs-001",
          type:           "IFS-Food",
          scope:          "food-processing",
          source:         "third-party",
          issuedBy:       "Bureau Veritas",
          issuedAt:       new Date("2025-01-15T00:00:00Z"),
          validUntil:     new Date("2027-01-15T00:00:00Z"),
          certificateUrl: "https://www.bureauveritas.ch/ifs/wander-001",
          verifiedByTomapo: true,
        },
      ],
      traceabilityScore: {
        completeness:         0.91,
        verifiedStations:     2,
        unknownStations:      0,
        hasGaps:              false,
        isThirdPartyVerified: true,
        blockchainHash:       "0x3a8f2c1d4e5b6a7c8d9e0f1a2b3c4d5e6f7a8b9c",
      },
      dataSources: [
        { id: "ds-ovo-001", type: "manufacturer", reliability: "high", name: "Wander AG", url: "https://www.ovomaltine.ch", fetchedAt: new Date("2026-03-05T07:00:00Z") },
        { id: "ds-ovo-002", type: "certification", reliability: "high", name: "IP-SUISSE", url: "https://www.ipsuisse.ch", fetchedAt: new Date("2026-03-05T07:01:00Z") },
      ],
      coldChainSummary: null,
      ingredients: [
        { ingredientType: "subProduct", chemical: null, subProduct: { barcode: null, productName: "Schweizer Gerste", brand: null, category: "grain", percentMin: 30, percentMax: 40, percentEstimate: 36, isTraceable: true, originCountry: "CH" } },
        { ingredientType: "subProduct", chemical: null, subProduct: { barcode: null, productName: "Kakao", brand: null, category: "cocoa", percentMin: 10, percentMax: 14, percentEstimate: 12, isTraceable: false, originCountry: "CI" } },
      ],
      createdAt: new Date("2026-03-05T07:00:00Z"),
      updatedAt: new Date("2026-03-05T07:00:00Z"),
    },

    // ═══════════════════════════════════════════════════
    // TRACE 3: Migros Vollmilch — kühlpflichtig
    // ═══════════════════════════════════════════════════
    {
      _id:               TRACE_IDS.milch,
      barcode:           PRODUCT_BARCODES.migrosMilch,
      batchId:           "MILCH-2026-0320",
      generatedAt:       new Date("2026-03-20T04:00:00Z"),
      requiresColdChain: true,
      alertIds:          [],
      stations: [
        {
          id:          "sta-milch-001",
          type:        "farming",
          status:      "completed",
          title:       "Milchwirtschaft Emmental",
          subtitle:    "Schweizer Heumilch-Betrieb",
          startedAt:   new Date("2026-03-18T04:00:00Z"),
          completedAt: new Date("2026-03-18T18:00:00Z"),
          durationHours: 14,
          co2KgPerKg:   1.85,
          isVerified:   true,
          verifiedBy:   "BioSuisse",
          notes:        "Heumilchbetrieb, Alpweidehaltung",
          wasRefrigerated: true,
          refrigerationTemperatureCelsius: 4,
          certificationIds: ["cert-heumilch-001"],
          location: {
            name:    "Alpbetrieb Zimmermann",
            country: "CH",
            region:  "Bern",
            city:    "Langnau im Emmental",
            address: null,
            latitude:  46.9394,
            longitude: 7.7879,
            embCode:   null,
            gln:       null,
          },
          qualityChecks: [
            {
              id:          "qc-milch-001",
              type:        "microbiological",
              status:      "passed",
              performedAt: new Date("2026-03-18T19:00:00Z"),
              performedBy: "Molkerei Qualitätskontrolle",
              accreditationNumber: "STS 0501",
              reportNumber: "MK-2026-0318-001",
              resultSummary: "Keimzahl und somatische Zellen im Normbereich",
              nextCheckDue: new Date("2026-04-18T00:00:00Z"),
              isMandatory:  true,
              detail: {
                laboratoryName:     "Schweizer Milchproduzenten SMP",
                iso17025Accredited: true,
                pathogensTested: [
                  { pathogen: "Listeria monocytogenes", testMethod: "ISO 11290", detected: false, cfuPerGram: 0, euLimitCfuPerGram: 0, limitExceeded: false, status: "passed" },
                  { pathogen: "Staphylococcus aureus", testMethod: "ISO 6888", detected: false, cfuPerGram: 10, euLimitCfuPerGram: 500, limitExceeded: false, status: "passed" },
                ],
              },
            },
          ],
          environmentSummary: { co2KgPerKg: 1.85, waterLiterPerKg: 628, energyKwhPerKg: 0.8, landUseM2PerKg: 9.2 },
          detail: {
            farmName:         "Alpbetrieb Zimmermann",
            farmingMethod:    "conventional",
            husbandrySystem:  "free-range",
            fertilizerType:   "organic",
            irrigationType:   "none",
            cropYieldTonsPerHectare: null,
            pesticidesUsed:   false,
            organicCertified: false,
            fieldCoordinates: [{ latitude: 46.9394, longitude: 7.7879, areaHectares: 18.5 }],
          },
        },
        {
          id:          "sta-milch-002",
          type:        "processing",
          status:      "completed",
          title:       "Pasteurisierung Zürich",
          subtitle:    "Molkerei & Abfüllung",
          startedAt:   new Date("2026-03-19T02:00:00Z"),
          completedAt: new Date("2026-03-19T18:00:00Z"),
          durationHours: 16,
          co2KgPerKg:   0.12,
          isVerified:   true,
          verifiedBy:   "Migros Qualität AG",
          notes:        "HTST-Pasteurisierung 72°C / 15 Sek.",
          wasRefrigerated: true,
          refrigerationTemperatureCelsius: 4,
          certificationIds: ["cert-iso22000-002"],
          location: {
            name:     "Molkerei Zürich",
            country:  "CH",
            region:   "Zürich",
            city:     "Zürich",
            address:  "Buckhauserstrasse 19, 8048 Zürich",
            latitude:  47.3785,
            longitude: 8.4980,
            embCode:  "CH-ZH 002 EG",
            gln:      "7610815000001",
          },
          qualityChecks: [],
          environmentSummary: { co2KgPerKg: 0.12, waterLiterPerKg: 3.5, energyKwhPerKg: 0.22, landUseM2PerKg: null },
          detail: {
            processType:  "pasteurisation",
            facilityName: "Molkerei Zürich Altstetten",
            haccp:        true,
            foodSafetyStandard: "FSSC22000",
            pasteurizationDetail: {
              method:              "HTST",
              temperatureCelsius:  72,
              durationSeconds:     15,
              logReduction:        6.0,
            },
          },
        },
        {
          id:          "sta-milch-003",
          type:        "transport",
          status:      "completed",
          title:       "Kühllieferung Migros Filialen",
          subtitle:    "Kühlkette Zürich Region",
          startedAt:   new Date("2026-03-20T02:00:00Z"),
          completedAt: new Date("2026-03-20T08:00:00Z"),
          durationHours: 6,
          co2KgPerKg:   0.03,
          isVerified:   true,
          verifiedBy:   "Camion Transport AG",
          notes:        "Durchgehende Kühlkette 2-6°C",
          wasRefrigerated: true,
          refrigerationTemperatureCelsius: 4,
          certificationIds: [],
          location: null,
          qualityChecks: [
            {
              id:          "qc-milch-002",
              type:        "temperature",
              status:      "passed",
              performedAt: new Date("2026-03-20T08:00:00Z"),
              performedBy: "Camion Transport Fahrenheit System",
              accreditationNumber: null,
              reportNumber: "CT-2026-0320-099",
              resultSummary: "Temperatur durchgehend 2-5°C",
              nextCheckDue: null,
              isMandatory:  true,
              detail: {
                measuredCelsius:   4.1,
                minAllowedCelsius: 2,
                maxAllowedCelsius: 6,
                isWithinRange:     true,
                sensorId:          "SENS-CT-0042",
                log: [
                  { timestamp: new Date("2026-03-20T02:00:00Z"), temperatureCelsius: 3.8, humidity: 85, isWithinRange: true },
                  { timestamp: new Date("2026-03-20T04:00:00Z"), temperatureCelsius: 4.2, humidity: 83, isWithinRange: true },
                  { timestamp: new Date("2026-03-20T06:00:00Z"), temperatureCelsius: 5.1, humidity: 82, isWithinRange: true },
                  { timestamp: new Date("2026-03-20T08:00:00Z"), temperatureCelsius: 4.0, humidity: 84, isWithinRange: true },
                ],
              },
            },
          ],
          environmentSummary: { co2KgPerKg: 0.03, waterLiterPerKg: null, energyKwhPerKg: 0.04, landUseM2PerKg: null },
          detail: {
            mode:          "road",
            carrierName:   "Camion Transport AG",
            distanceKm:    95,
            fuelType:      "diesel",
            co2EmissionsKg: 0.03,
            tempControlled: true,
            tempMinCelsius: 2,
            tempMaxCelsius: 6,
          },
        },
      ],
      environmentSummary: {
        co2TotalKgPerKg:            2.0,
        ecoscoreGrade:              "c",
        ecoscoreScore:              45,
        waterFootprintLiterPerKg:   631,
        waterStressScore:           0.38,
        forestFootprintM2PerKg:     null,
        forestFootprintGrade:       null,
        deforestationRisk:          null,
        transportEmissionsGramsCo2: 30,
        totalTransportDistanceKm:   95,
        transportLegCount:          1,
        packagingCo2Kg:             0.04,
        packagingScore:             68,
        recyclablePackagingPercent: 1.0,
        productionSystemBonus:      3,
        originEpiScore:             72,
        co2ByPhase: {
          agriculture:    1.85,
          processing:     0.12,
          transportation: 0.03,
          packaging:      0.04,
          distribution:   0.03,
          consumption:    null,
        },
        threatenedSpeciesRisk: null,
      },
      certifications: [
        {
          id:             "cert-heumilch-001",
          type:           "SwissHeumilch",
          scope:          "farming",
          source:         "third-party",
          issuedBy:       "IG Schweizer Heumilch",
          issuedAt:       new Date("2025-03-01T00:00:00Z"),
          validUntil:     new Date("2026-02-28T00:00:00Z"),
          certificateUrl: null,
          verifiedByTomapo: false,
        },
        {
          id:             "cert-iso22000-002",
          type:           "ISO22000",
          scope:          "food-safety",
          source:         "third-party",
          issuedBy:       "SGS SA",
          issuedAt:       new Date("2023-09-01T00:00:00Z"),
          validUntil:     new Date("2026-09-01T00:00:00Z"),
          certificateUrl: "https://www.sgs.com/certifications/iso22000/migros-molkerei-001",
          verifiedByTomapo: true,
        },
      ],
      traceabilityScore: {
        completeness:         0.94,
        verifiedStations:     3,
        unknownStations:      0,
        hasGaps:              false,
        isThirdPartyVerified: true,
        blockchainHash:       null,
      },
      dataSources: [
        { id: "ds-milch-001", type: "manufacturer", reliability: "high", name: "Migros Genossenschafts-Bund", url: "https://www.migros.ch", fetchedAt: new Date("2026-03-20T04:00:00Z") },
      ],
      coldChainSummary: {
        isCompliant:               true,
        totalRefrigeratedHours:    36,
        totalUnrefrigeratedHours:  0,
        maxTemperatureCelsius:     5.1,
        minTemperatureCelsius:     2.0,
        avgTemperatureCelsius:     4.0,
        breakCount:                0,
        breaks:                    [],
        storageDetails: [
          { stationId: "sta-milch-001", facilityName: "Alpbetrieb Zimmermann", tempMinCelsius: 2, tempMaxCelsius: 5, humidityPercent: null, durationHours: 14 },
          { stationId: "sta-milch-002", facilityName: "Molkerei Zürich", tempMinCelsius: 2, tempMaxCelsius: 5, humidityPercent: 80, durationHours: 16 },
        ],
      },
      ingredients: [
        { ingredientType: "subProduct", chemical: null, subProduct: { barcode: null, productName: "Schweizer Rohmilch", brand: null, category: "dairy", percentMin: 100, percentMax: 100, percentEstimate: 100, isTraceable: true, originCountry: "CH" } },
      ],
      createdAt: new Date("2026-03-20T04:00:00Z"),
      updatedAt: new Date("2026-03-20T04:00:00Z"),
    },

    // ═══════════════════════════════════════════════════
    // TRACE 4: Lindt Excellence 85% — mit aktivem Recall-Alert
    // ═══════════════════════════════════════════════════
    {
      _id:               TRACE_IDS.lindt,
      barcode:           PRODUCT_BARCODES.lindt85,
      batchId:           "LINDT-85-2026-0201",
      generatedAt:       new Date("2026-02-15T09:00:00Z"),
      requiresColdChain: false,
      alertIds:          [],  // wird nach Alert-Seed befüllt
      stations: [
        {
          id:          "sta-lindt-001",
          type:        "farming",
          status:      "completed",
          title:       "Kakaoplantage Ghana",
          subtitle:    "Rainforest Alliance zertifiziert",
          startedAt:   new Date("2025-09-01T00:00:00Z"),
          completedAt: new Date("2025-11-30T00:00:00Z"),
          durationHours: 2160,
          co2KgPerKg:   2.1,
          isVerified:   true,
          verifiedBy:   "Rainforest Alliance",
          notes:        "Ashanti Region, Ghana. RA-zertifizierter Kooperativenbetrieb.",
          wasRefrigerated: false,
          refrigerationTemperatureCelsius: null,
          certificationIds: ["cert-ra-001"],
          location: {
            name:    "Cocoa Farmers Cooperative Ashanti",
            country: "GH",
            region:  "Ashanti",
            city:    "Kumasi",
            address: null,
            latitude:  6.6882,
            longitude: -1.6244,
            embCode:   null,
            gln:       null,
          },
          qualityChecks: [],
          environmentSummary: { co2KgPerKg: 2.1, waterLiterPerKg: 27000, energyKwhPerKg: 0.5, landUseM2PerKg: 22.0 },
          detail: {
            farmName:         "Cooperative Ashanti Region",
            farmingMethod:    "conventional",
            husbandrySystem:  null,
            fertilizerType:   "organic",
            irrigationType:   "rain-fed",
            cropYieldTonsPerHectare: 0.5,
            pesticidesUsed:   false,
            organicCertified: false,
            fieldCoordinates: [{ latitude: 6.6882, longitude: -1.6244, areaHectares: 2800 }],
          },
        },
        {
          id:          "sta-lindt-002",
          type:        "processing",
          status:      "completed",
          title:       "Schokoladenproduktion Kilchberg",
          subtitle:    "Lindt & Sprüngli Hauptwerk",
          startedAt:   new Date("2026-01-15T06:00:00Z"),
          completedAt: new Date("2026-02-10T18:00:00Z"),
          durationHours: 612,
          co2KgPerKg:   0.65,
          isVerified:   true,
          verifiedBy:   "Bureau Veritas",
          notes:        "Conchierzeit 72h für Excellence-Linie",
          wasRefrigerated: false,
          refrigerationTemperatureCelsius: null,
          certificationIds: ["cert-ifs-lindt-001"],
          location: {
            name:     "Lindt & Sprüngli AG",
            country:  "CH",
            region:   "Zürich",
            city:     "Kilchberg",
            address:  "Seestrasse 204, 8802 Kilchberg",
            latitude:  47.3228,
            longitude: 8.5489,
            embCode:   "CH-ZH 008 EG",
            gln:       "7610300000001",
          },
          qualityChecks: [
            {
              id:          "qc-lindt-001",
              type:        "chemical",
              status:      "passed",
              performedAt: new Date("2026-02-08T10:00:00Z"),
              performedBy: "Lindt QA",
              accreditationNumber: "STS 0620",
              reportNumber: "LINDT-QC-2026-0208",
              resultSummary: "Cadmium-Gehalt unter EU-Grenzwert",
              nextCheckDue: null,
              isMandatory: true,
              detail: {
                laboratoryName: "Lindt Internes Prüflabor",
                testMethod: "ICP-MS",
                substancesTested: [
                  { substance: "Cadmium", category: "heavy-metal", measuredMgPerKg: 0.28, limitMgPerKg: 0.80, limitExceeded: false, status: "passed" },
                  { substance: "Blei",    category: "heavy-metal", measuredMgPerKg: 0.04, limitMgPerKg: 0.10, limitExceeded: false, status: "passed" },
                ],
              },
            },
          ],
          environmentSummary: { co2KgPerKg: 0.65, waterLiterPerKg: 15, energyKwhPerKg: 1.8, landUseM2PerKg: null },
          detail: {
            processType:  "mixing",
            facilityName: "Lindt & Sprüngli Kilchberg",
            haccp:        true,
            foodSafetyStandard: "IFS",
          },
        },
      ],
      environmentSummary: {
        co2TotalKgPerKg:            2.75,
        ecoscoreGrade:              "c",
        ecoscoreScore:              41,
        waterFootprintLiterPerKg:   27015,
        waterStressScore:           0.6,
        forestFootprintM2PerKg:     22.0,
        forestFootprintGrade:       "d",
        deforestationRisk:          0.45,
        transportEmissionsGramsCo2: 185,
        totalTransportDistanceKm:   6500,
        transportLegCount:          2,
        packagingCo2Kg:             0.08,
        packagingScore:             60,
        recyclablePackagingPercent: 0.8,
        productionSystemBonus:      0,
        originEpiScore:             38,
        co2ByPhase: {
          agriculture:    2.1,
          processing:     0.65,
          transportation: 0.185,
          packaging:      0.08,
          distribution:   0.02,
          consumption:    null,
        },
        threatenedSpeciesRisk: {
          ingredient:      "Kakao",
          ecoscorePenalty: -8,
          explanation:     "Kakaoproduktion in Ghana mit Risiko für Regenwaldflächen",
        },
      },
      certifications: [
        {
          id:             "cert-ra-001",
          type:           "RainforestAlliance",
          scope:          "farming",
          source:         "third-party",
          issuedBy:       "Rainforest Alliance",
          issuedAt:       new Date("2024-09-01T00:00:00Z"),
          validUntil:     new Date("2026-08-31T00:00:00Z"),
          certificateUrl: "https://www.rainforest-alliance.org/certificate/lindt-001",
          verifiedByTomapo: true,
        },
      ],
      traceabilityScore: {
        completeness:         0.78,
        verifiedStations:     2,
        unknownStations:      1,
        hasGaps:              true,
        isThirdPartyVerified: true,
        blockchainHash:       null,
      },
      dataSources: [
        { id: "ds-lindt-001", type: "manufacturer", reliability: "high", name: "Lindt & Sprüngli AG", url: "https://www.lindt.ch", fetchedAt: new Date("2026-02-15T09:00:00Z") },
      ],
      coldChainSummary: null,
      ingredients: [
        { ingredientType: "subProduct", chemical: null, subProduct: { barcode: null, productName: "Kakaomasse Ghana", brand: null, category: "cocoa", percentMin: 80, percentMax: 90, percentEstimate: 85, isTraceable: true, originCountry: "GH" } },
        { ingredientType: "subProduct", chemical: null, subProduct: { barcode: null, productName: "Kakaobutter", brand: null, category: "cocoa", percentMin: null, percentMax: null, percentEstimate: null, isTraceable: false, originCountry: "GH" } },
      ],
      createdAt: new Date("2026-02-15T09:00:00Z"),
      updatedAt: new Date("2026-02-15T09:00:00Z"),
    },
  ];

  await db.collection("traces").insertMany(traces);
  console.log(`   ✓ Traces: ${traces.length} inserted`);
  return traces;
}